version: '3.4'

services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ReDev 
      MYSQL_USER: behrad
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
  resumerankingmaster:
    depends_on:
      - db
    image: resumerankingmaster
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  dbdata:
