version: '3.4'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ReDev 
      MYSQL_USER: behrad
      MYSQL_PASSWORD: 1234

  resumerankingmaster:
    depends_on:
      - db
    image: resumerankingmaster
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./Dockerfile
