version: '3.4'

services:
  resumerankingmaster:
    image: resumerankingmaster
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  dbdata:
